name: Update submodules references

on:
  push:
    branches: [ main ]
    paths:
      - 'client/**'
      - 'server/**'

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout parent repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update submodules to latest commit
        run: |
          git submodule update --remote --recursive
          git add client server
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m "chore: update submodules to latest commit" || echo "No changes to commit"
          git push
